export * from 'app/modules/onboarding/pages/background-check/background-check.component';
export * from 'app/modules/onboarding/pages/finishing-up/finishing-up.component';
export * from 'app/modules/onboarding/pages/onboarding-index/onboarding-index.component';
export * from 'app/modules/onboarding/pages/paychex-complete/paychex-complete.component';
export * from 'app/modules/onboarding/pages/payoneer-complete/payoneer-complete.component';
export * from 'app/modules/onboarding/pages/setup-payment/setup-payment.component';
export * from 'app/modules/onboarding/pages/setup-residence/setup-residence.component';
export * from 'app/modules/onboarding/pages/setup-tracker/setup-tracker.component';
export * from 'app/modules/onboarding/pages/welcome/welcome.component';
