export const MANAGER_BUTTONS = [
  {
    displayText: 'Accounts',
    class: 'app-icon__accounts',
    identifier: 'ACCOUNTS',
    link: '',
  },
  {
    displayText: 'Team Summary',
    class: 'app-icon__team-summary',
    identifier: 'TEAM_SUMMARY',
    link: '/contractor/team-summary',
  },
  {
    displayText: 'Timesheet',
    class: 'app-icon__timesheet',
    identifier: 'TIMESHEET',
    link: '/contractor/timesheet',
  },
  {
    displayText: 'Activities',
    class: 'app-icon__activities',
    identifier: 'ACTIVITIES',
    link: '/contractor/team-activities',
  },
  {
    displayText: 'Metrics',
    class: 'app-icon__metrics',
    identifier: 'METRICS',
    link: '/contractor/team-metrics',
  },
  {
    displayText: 'Team History',
    class: 'app-icon__team-history',
    identifier: 'TEAM_HISTORY',
    link: '',
  },
  {
    displayText: 'Workflows',
    class: 'app-icon__workflows',
    identifier: 'WORKFLOWS',
    link: '',
  },
  {
    displayText: 'Gemba Walk',
    class: 'app-icon__gemba-walk',
    identifier: 'GEMBA_WALK',
    link: '',
  },
  {
    displayText: 'World',
    class: 'app-icon__world',
    identifier: 'WORLD',
    link: '/world',
  },
  {
    displayText: 'Organization',
    class: 'app-icon__organization',
    identifier: 'ORGANIZATION',
    link: '/contractor/team-organization',
  },
  {
    displayText: 'Hire',
    class: 'app-icon__hire',
    identifier: 'HIRE',
    link: '',
  },
  {
    displayText: 'Reports',
    class: 'app-icon__reports',
    identifier: 'REPORTS',
    link: '',
  },
  {
    displayText: 'Team Settings',
    class: 'app-icon__team-settings',
    identifier: 'TEAM_SETTINGS',
    link: '/contractor/team-settings',
  },
  {
    displayText: 'Timezones',
    class: 'app-icon__timezones',
    identifier: 'TIMEZONES',
    link: '/contractor/timezones',
  },
  {
    displayText: 'Check-in Chats',
    class: 'app-icon__check-in-chats',
    identifier: 'CHECKIN_CHATS',
    link: '/contractor/check-in-chats',
  },
  {
    displayText: 'Rank & Review',
    class: 'app-icon__rand-and-review',
    identifier: 'RANK_AND_REVIEW',
    link: '/contractor/rank-and-review',
  },
  {
    displayText: 'Goals',
    class: 'app-icon__goals',
    identifier: 'GOALS',
    link: '',
  },
  {
    displayText: 'Polls',
    class: 'app-icon__polls',
    identifier: 'TEAM_POLLS',
    link: '',
  },
  {
    displayText: 'Scoring',
    class: 'app-icon__scoring',
    identifier: 'TEAM_SCORING',
    link: '',
  },
  {
    displayText: 'My Dashboard',
    class: 'app-icon__dashboard',
    identifier: 'MY_DASHBOARD',
    link: '/contractor/my-dashboard/summary',
  },
  {
    displayText: 'Learn',
    class: 'app-icon__learn',
    identifier: 'LEARN',
    externalUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSc2KRh6GizJ5tdkil8xsAVAS3vq-bQEP5bc4D8EkjAZFdR7PA/viewform?c=0&w=1',
  },
  {
    displayText: 'Community',
    class: 'app-icon__community',
    identifier: 'COMMUNITY',
    externalUrl: 'https://www.facebook.com/groups/219726845099754',
  },
  {
    displayText: 'Time Approval',
    class: 'app-icon__time-approval',
    identifier: 'MANUAL_TIME_APPROVAL',
    link: '',
  },
  {
    displayText: 'WorkSmart',
    class: 'app-icon__worksmart',
    identifier: 'WORK_SMART',
    worksmartUrl: 'https://worksmart-%(env)s.crossover.com/#/login?otp=%(contractorId)s:%(date)s:%(token)s',
  },
];
