export interface EnumsResponse {
  statuses: string[];
  salaryUnits: string[];
  salaryTypes: string[];
  teamFeatures: string[];
  appFeatures: string[];
  assignmentFeatures: string[];
  genders: string[];
  flowTypes: string[];
  invoiceStatuses: string[];
  jobStatuses: string[];
  marketplaceMemberStatuses: string[];
  paymentInfoStatuses: string[];
  paymentInfoTypes: string[];
  preMarketplaceInterviewCallStatuses: string[];
  preMarketplaceInterviewStatus: string[];
  preMarketplaceQuestions: string[];
  selectionStatuses: string[];
  workDiaryPeriods: string[];
  paymentPlatforms: string[];
  degreeTypes: string[];
  checkinStatuses: string[];
  securityQuestions: string[];
  applicationStatuses: string[];
  applicationTypes: string[];
  assignmentStatuses: string[];
  candidateAvailabilities: string[];
  interviewStatuses: string[];
}
